// TX PRBS generator structural checks (TEST_CHECKLIST.md category 5.3,
// TX_009-011). Deliberately TX-only (no CDR/RX involvement at all): the
// generator's own correctness is fully observable via the digital
// hierarchical probe below (tb_top.u_system.dut.u_top.u_pcs.u_tx.
// u_prbs_generator, following the same hierarchical-reference convention
// as uvm_tb/tests/test_mode_test.sv), so this test sidesteps the
// analog-CDR-loop limitation documented in
// docs/implementation/00-fixes-applied.md section 6 entirely - there's no
// reason a whitebox check of the generator's own LFSR needs to survive a
// full loopback round trip.
//
// TX_012 ("PRBS bypasses FIFO when enabled") is a description of
// serdesphy_tx_data_mux.v's TX_DATA_SEL=0 selection behavior, not a
// distinct runtime behavior of the generator itself - already covered by
// REG_015 (TEST_CHECKLIST.md 3.4) selecting the PRBS source and this test
// then observing real PRBS bytes flow with TX_FIFO_EN left at its
// power-on default (disabled) throughout, i.e. genuinely never touching
// the FIFO path.

class prbs_generator_test extends uvm_test;

  `uvm_component_utils(prbs_generator_test)

  serdesphy_env      env;
  virtual system_if  vif;
  bit                last_got;

  function new(string name = "prbs_generator_test", uvm_component parent = null);
    super.new(name, parent);
  endfunction

  function void build_phase(uvm_phase phase);
    super.build_phase(phase);
    env = serdesphy_env::type_id::create("env", this);
    if (!uvm_config_db#(virtual system_if)::get(this, "", "vif", vif))
      `uvm_fatal("NOVIF", "prbs_generator_test: virtual interface not set via uvm_config_db")
  endfunction

  task automatic wait_pll_lock(input realtime timeout_ns);
    last_got = 1'b0;
    fork : pll_wait_blk
      begin
        wait (vif.pll_lock == 1'b1);
        last_got = 1'b1;
      end
      begin
        #(timeout_ns * 1ns);
      end
    join_any
    disable pll_wait_blk;
  endtask : wait_pll_lock

  // Independent reference model of the x^7+x^6+1 PRBS-7 recurrence -
  // written from the polynomial definition (docs/info.md 5.4), not
  // copied from serdesphy_prbs_generator.v's prbs7_advance_byte, so a
  // match against the DUT's actual output bytes is a real independent
  // check of TX_009, not a tautology.
  function automatic byte ref_prbs_next(ref bit [6:0] state);
    bit [6:0] s;
    byte      b;
    bit       fb;
    begin
      s = state;
      for (int i = 0; i < 8; i++) begin
        fb   = s[6] ^ s[5];
        b[7-i] = fb;
        s    = {s[5:0], fb};
      end
      state = s;
      return b;
    end
  endfunction

  task run_phase(uvm_phase phase);
    system_init_vseq init_seq;
    bit [6:0]         ref_state;
    byte              expected, actual;
    realtime          t_prev, t_now;
    int                n_checked;

    phase.raise_objection(this);

    init_seq = system_init_vseq::type_id::create("init_seq");
    init_seq.start(env.vseqr);

    wait_pll_lock(50_000);
    if (!last_got) begin
      `uvm_error("PRBS_GEN", "PLL_LOCK did not assert - cannot proceed")
      phase.drop_objection(this);
      return;
    end

    // TX_009/TX_010/TX_012: TX_EN + TX_PRBS_EN, TX_FIFO_EN left at its
    // power-on default (0) and DATA_SELECT left at its power-on default
    // (TX_DATA_SEL=0, PRBS source - REG_015) - the FIFO path is never
    // touched at all here.
    env.regmodel.write_reg_by_addr(system_pkg::REG_TX_CONFIG, 8'h05, null);

    t_prev    = -1.0;
    n_checked = 0;

    // Sample 21 consecutive generated bytes directly off
    // serdesphy_tx_data_mux.v's OUTPUT (to the Manchester encoder), not
    // serdesphy_prbs_generator.v's own prbs_valid/prbs_data ports
    // directly: the generator<->mux handshake can legitimately re-assert
    // the generator's own prbs_valid across more than one clk_24m cycle
    // for the *same* already-captured word while the mux is busy (a
    // cross-coupled two-FSM handshake quirk, not a data-correctness bug -
    // confirmed by mux_valid/mux_data faithfully producing exactly one
    // clean pulse per real transmitted byte regardless). mux_valid/
    // mux_data is also the more representative point for TX_009 anyway,
    // since it's what actually reaches the encoder.
    //
    // The first captured word (i==0) seeds the reference model's LFSR
    // state directly from its own low 7 bits rather than being compared:
    // write_reg_by_addr's I2C transaction takes tens of us to physically
    // transmit, and TX_EN/TX_PRBS_EN can - and does - take effect
    // partway through it, well before this task returns, so by the time
    // this loop starts the generator has already been running for a
    // while, quite possibly already parked in STATE_OUTPUT holding a
    // byte it has computed but this mux hasn't captured yet - i.e. there
    // is no reliably race-free instant to snapshot "the state before the
    // very next captured word" from outside. Self-syncing from the first
    // observed byte instead (same technique used for the same underlying
    // reason in serdesphy_prbs_checker.v - see
    // docs/implementation/00-fixes-applied.md section 6) sidesteps the
    // race entirely: per this same LFSR recurrence, the state right
    // after producing a byte is exactly that byte's own low 7 bits, so
    // every word from the *second* one on is still checked against the
    // independent reference model's own recurrence, not read from the
    // DUT.
    for (int unsigned i = 0; i < 21; i++) begin
      @(posedge tb_top.u_system.dut.u_top.u_pcs.u_tx.u_tx_data_mux.mux_valid);
      t_now  = $realtime;
      actual = tb_top.u_system.dut.u_top.u_pcs.u_tx.u_tx_data_mux.mux_data;
      if (i == 0) begin
        ref_state = actual[6:0];
      end else begin
        expected = ref_prbs_next(ref_state);
        if (actual !== expected) begin
          `uvm_error("PRBS_GEN",
                     $sformatf("TX_009: word %0d mismatch - dut=0x%02h ref=0x%02h (polynomial x^7+x^6+1 not matched)",
                                i, actual, expected))
        end
        n_checked++;
      end

      // TX_011: update rate = 24MHz - each new word should appear on a
      // clk_24m boundary, i.e. every valid-to-valid interval should be a
      // whole-number multiple of the reference clock period, not some
      // unrelated (e.g. 240MHz-domain) cadence.
      if (t_prev >= 0.0) begin
        real delta, n_periods, remainder;
        delta     = real'(t_now - t_prev);
        n_periods = $rtoi((delta / `SERDESPHY_REF_CLK_PERIOD_NS) + 0.5);
        remainder = delta - (`SERDESPHY_REF_CLK_PERIOD_NS * n_periods);
        if (remainder > 0.5 || remainder < -0.5)
          `uvm_error("PRBS_GEN",
                     $sformatf("TX_011: word %0d arrived %0.3fns after the previous one - not a whole multiple of the %0.3fns reference clock period",
                                i, delta, `SERDESPHY_REF_CLK_PERIOD_NS))
      end
      t_prev = t_now;
    end

    if (n_checked == 20)
      `uvm_info("PRBS_GEN",
                 "TX_009/TX_010/TX_011/TX_012: 20 consecutive PRBS-7 bytes matched an independent x^7+x^6+1 reference model, each landing on a clk_24m boundary, with the FIFO path untouched throughout - OK",
                 UVM_LOW)

    phase.drop_objection(this);
  endtask : run_phase

endclass : prbs_generator_test
